---
output:
  github_document
---

# IK2023 - MC2

This is the accompanying repository for the method course **MC2: Tracking the embodied dynamics of cognition using computer mouse tracking** by [Stefan Scherbaum](https://tu-dresden.de/Members/stefan.scherbaum) and [Martin Schoemann](https://tu-dresden.de/Members/martin.schoemann) during the [Interdisciplinary College 2023](https://interdisciplinary-college.org/) (03/12/-03/17/2023).

## What you need

During the course, you need some software that we ask you to have prepared prior to the first session on Tuesday.

1.  [OpenSesame](https://osdoc.cogsci.nl/3.3/) with the [mousetrap plugin](https://github.com/PascalKieslich/mousetrap-os)
2.  A scientific computing software of your choice
    -   [R](https://www.r-project.org/) (preferably in [RStudio](https://posit.co/products/open-source/rstudio/)), or
    -   [Matlab](https://www.mathworks.com/products/matlab.html) (including the [TCMR toolbox](osf.io/5e3vn))


## What you might read

Here, we provide some open-access literature that you might want to read between the sessions or after the course.
During the course, we cover the papers' content only partially, so you can gain much more insights into mouse tracking by reading them.  

- [Freeman (2018: CDPS)](https://doi.org/10.1177/0963721417746793)
- [Scherbaum & Dshemuchadse (2020: M&C)](https://doi.org/10.3758/s13421-019-00981-x)
- [Schoemann et al. (2021: PBR)](https://doi.org/10.3758/s13423-020-01851-3)
- [Wulff et al. (2022: preprint)](https://doi.org/10.31234/osf.io/v685r)

